### ISSUE TITLE
Uncaught TypeError: Cannot read property 'start' of undefined

### ISSUE THREAD

**Issue by Cartman0** [aki77/atom-japan-util#1]
[Enter steps to reproduce below:]
1. selected document.
2. hankaku only ascii

**Atom Version**: 1.5.3
**System**: Unknown Windows Version
**Thrown From**: [japan-util](https://github.com/aki77/atom-japan-util) package, v0.1.1
### Stack Trace

Uncaught TypeError: Cannot read property 'start' of undefined

```
At C:\Users\nabana\.atom\packages\japan-util\node_modules\moji\src\moji.core.js:184

TypeError: Cannot read property 'start' of undefined
    at Moji._mojisyuType (C:\Users\nabana\.atom\packages\japan-util\node_modules\moji\src\moji.core.js:184:16)
    at Moji.convert (C:\Users\nabana\.atom\packages\japan-util\node_modules\moji\src\moji.core.js:32:14)
    at Object.module.exports.convert (file:///C:/Users/nabana/.atom/packages/japan-util/lib/main.coffee:34:34)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\nabana\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (C:\Users\nabana\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\nabana\AppData\Local\atom\app-1.5.3\resources\app.asar\src\command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (C:\Users\nabana\AppData\Local\atom\app-1.5.3\resources\app.asar\src\atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -3:50.7.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -3:47 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:46.3.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:43.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:42.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  2x -3:39.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:38.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -3:38.4.0 japan-util:hankaku-only-ascii (atom-text-editor.editor)
     -3:25.7.0 core:select-all (atom-text-editor.editor.is-focused)
     -3:24.2.0 command-palette:toggle (atom-text-editor.editor.is-focused)
  3x -3:21.6.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -3:21 core:move-up (atom-text-editor.editor.mini.is-focused)
     -3:20.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -3:20.7.0 japan-util:hankaku-only-ascii (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "autocomplete-paths",
      "linter-tidy",
      "redpen",
      "linter-javac",
      "ConvertToUtf8Plus",
      "java-importer",
      "wordpress-api",
      "language-babel",
      "linter-eslint"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-minify, v0.7.1
color-picker, v2.1.1
compare-files, v0.6.2
compass, v0.9.1
css-snippets, v0.9.0
emmet, v2.4.1
file-icons, v1.6.14
japan-util, v0.1.1
javascript-snippets, v1.0.0
jquery-snippets, v11.0.0
linter, v1.11.3
linter-csslint, v1.1.0
linter-htmlhint, v0.2.1
linter-scss-lint, v2.5.0
minimap, v4.16.0
minimap-color-highlight, v4.1.4
project-manager, v2.6.5
show-ideographic-space, v1.0.1
Sublime-Style-Column-Selection, v1.5.1
symbols-tree-view, v0.10.1
web-browser, v1.5.0

# Dev
No dev packages
```

**Comment by aki77** [comment]
Please try the latest version.
